# Generated by Django 4.1.1 on 2023-01-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchollershipList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000)),
                ('elligiblity', models.CharField(max_length=500)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('applicationURL', models.URLField(max_length=100)),
                ('image', models.ImageField(upload_to='schollershipImage')),
            ],
        ),
    ]
