# Generated by Django 4.1.1 on 2023-01-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSapp', '0002_schollershiplist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schollershiplist',
            name='body',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='schollershiplist',
            name='elligiblity',
            field=models.TextField(max_length=500),
        ),
    ]
